### ISSUE TITLE
Redirects are treated as error

### ISSUE THREAD

**Issue by hashrock** [jaredkrinke/link_checker#4]
Currently, the HTTP status 30x appears to be treated as an error. I'm not sure how should the link checker handle this, but it's nice to have an option which treats redirects as ok. What do you think?

**Comment by jaredkrinke** [comment]
My opinion is that a redirect should cause it to validate the new location. Obviously, the code doesn't do this today. Thanks for bringing this up!

Aside: are you using this link checker for anything you're willing to share? My impression was that no one was actually using this link checker (except for me, obviously) :)

**Comment by hashrock** [comment]
I was wondering if this could be used to check deno documentation sites(such as [fresh docs](https://github.com/denoland/fresh), [dotland](https://github.com/denoland/dotland/)). During verification, I found a problem with fresh(web framework) not responding to HEAD requests😅

**Comment by jaredkrinke** [comment]
I'm now thinking that 3XX responses should be treated as successful, with a command line option to then check the new location (or report an error if no Location header was provided).

It sounds like these responses differ from server to server, and some even put the location in the response body instead of a header, so it could be tricky to validate...

**Comment by jaredkrinke** [comment]
@hashrock do you have an example site I could test against?

It looks like `fetch` itself can handle redirects internally, so the solution might be as simple as adding `redirect: "follow"` to the `fetch` options, but I haven't actually been able to find a site where the current implementation reports a broken link due to a redirect :)

Edit: fetch's default is to follow redirects, so this should be working.

**Comment by hashrock** [comment]
@jaredkrinke 
Sorry, I think I misreported this Issue.

I was using the following site for testing, but this site did not respond to HEAD in the first place due to a bug in fresh, so I was testing it while modifying link_checker. I think that modification probably led to the redirect error.

https://deno.com/blog

I created a verification website with a version of fresh that fixes the bug, and you are right, the Redirect is working fine.

https://github.com/hashrock-sandbox/link-checker-test-fixture

Thanks for doing the research!
